site_name: MD-Models
repo_url: https://github.com/JR-1991/md-models
edit_uri: edit/main/docs/
theme:
  font:
    text: Open Sans
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow
    - search.suggest
    - content.action.edit
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
nav:
  - Home: index.md
  - Syntax:
      - "Overview": syntax/index.md
      - "Types": syntax/types.md
      - "Enumerations": syntax/enumerations.md
      - "Ontologies": syntax/ontologies.md
      - "Configuration": syntax/configuration.md
  - Library:
      - "Overview": library/index.md
      - "Validation": library/validation.md
      - "Conversion": library/conversion.md
      - "Code Generation": library/code-generation.md
      - "Continuous integration": library/pipelines.md
  - "Data Types":
      - "Overview": types/index.md
      - "Equation": types/equation.md
      - "Unit Definition": types/unit-definition.md
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
plugins:
  - search
