name: Documentation

on:
  push:
    branches:
      - "add-docs"
    paths:
      - "docs/**"
      - "mkdocs.yml"

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ github.ref }}
      - run: pip install mkdocs-material jupyter nbconvert mkdocs-jupyter
      - run: mkdocs gh-deploy --force
