name: Publish to NPM (Web CDN)

on:
  release:
    types: [ published ]

permissions:
  contents: write
  id-token: write

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Build WASM for npm (bundle)
        run: wasm-pack build --release --out-name mdmodels-web --target web --features wasm

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Update package name
        run: |
          jq '.name = "mdmodels-web"' pkg/package.json > pkg/package.json.tmp
          mv pkg/package.json.tmp pkg/package.json

      - run: |
          cd pkg/
          npm install --package-lock-only
          npm ci
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
